apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  ports:
  - protocol: "TCP"
    port: 18080
    targetPort: 5000
  selector:
    app: flask-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: docker.io/mcwilson73/personal:latest
        env:
          - name: FLASK_APP
            value: app
        ports:
        - name: http
          containerPort: 8081
        - name: https
          containerPort: 8444
        volumeMounts:
        - name: client-secrets
          mountPath: /tmp/
      volumes:
      - name: client-secrets
        secret:
          secretName: client-secrets
          items:
            - key: client_secrets.json
              path: client_secrets.json
